//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 04:16:58 PM PST 
//


package com.pacsun.inventory.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.InventoryList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.InventoryList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.demandware.com/xml/impex/inventory/2007-05-31}complexType.Header"/>
 *         &lt;element name="records" type="{http://www.demandware.com/xml/impex/inventory/2007-05-31}complexType.InventoryRecords" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.InventoryList", namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31", propOrder = {
    "header",
    "records"
})
public class ComplexTypeInventoryList {

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31", required = true)
    protected ComplexTypeHeader header;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/inventory/2007-05-31")
    protected ComplexTypeInventoryRecords records;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeHeader }
     *     
     */
    public ComplexTypeHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeHeader }
     *     
     */
    public void setHeader(ComplexTypeHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeInventoryRecords }
     *     
     */
    public ComplexTypeInventoryRecords getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeInventoryRecords }
     *     
     */
    public void setRecords(ComplexTypeInventoryRecords value) {
        this.records = value;
    }

}
