//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 10:04:57 AM PDT 
//


package com.pacsun.store.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Store complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Store">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="address1" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="address2" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="city" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="postal-code" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="state-code" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="country-code" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.CountryCode" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Email" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.PhoneNumber" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.PhoneNumber" minOccurs="0"/>
 *         &lt;element name="store-events" type="{http://www.demandware.com/xml/impex/store/2007-04-30}sharedType.LocalizedText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="store-hours" type="{http://www.demandware.com/xml/impex/store/2007-04-30}sharedType.LocalizedText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/store/2007-04-30}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="store-id" use="required" type="{http://www.demandware.com/xml/impex/store/2007-04-30}simpleType.Generic.NonEmptyString.256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Store", propOrder = {
    "name",
    "address1",
    "address2",
    "city",
    "postalCode",
    "stateCode",
    "countryCode",
    "email",
    "phone",
    "fax",
    "storeEvents",
    "storeHours",
    "image",
    "latitude",
    "longitude",
    "customAttributes"
})
public class ComplexTypeStore {

    protected String name;
    protected String address1;
    protected String address2;
    protected String city;
    @XmlElement(name = "postal-code")
    protected String postalCode;
    @XmlElement(name = "state-code")
    protected String stateCode;
    @XmlElement(name = "country-code")
    protected String countryCode;
    protected String email;
    protected String phone;
    protected String fax;
    @XmlElement(name = "store-events")
    protected List<SharedTypeLocalizedText> storeEvents;
    @XmlElement(name = "store-hours")
    protected List<SharedTypeLocalizedText> storeHours;
    protected String image;
    protected BigDecimal latitude;
    protected BigDecimal longitude;
    @XmlElement(name = "custom-attributes")
    protected SharedTypeCustomAttributes customAttributes;
    @XmlAttribute(name = "store-id", required = true)
    protected String storeId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the stateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCode() {
        return stateCode;
    }

    /**
     * Sets the value of the stateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCode(String value) {
        this.stateCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the storeEvents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storeEvents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoreEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedText }
     * 
     * 
     */
    public List<SharedTypeLocalizedText> getStoreEvents() {
        if (storeEvents == null) {
            storeEvents = new ArrayList<SharedTypeLocalizedText>();
        }
        return this.storeEvents;
    }

    /**
     * Gets the value of the storeHours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storeHours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoreHours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedText }
     * 
     * 
     */
    public List<SharedTypeLocalizedText> getStoreHours() {
        if (storeHours == null) {
            storeHours = new ArrayList<SharedTypeLocalizedText>();
        }
        return this.storeHours;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the storeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * Sets the value of the storeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreId(String value) {
        this.storeId = value;
    }

}
