//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 10:04:57 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demandware.com/xml/impex/store/2007-04-30", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pacsun.store.jaxb;
