DROP TABLE JKIM2.Student;
CREATE TABLE JKIM2.Student(
  STUDENT_ID	INTEGER 		NOT NULL,
  STUDENT_NAME	VARCHAR(45)		NOT NULL,
  STUDENT_ADDRESS	VARCHAR(45)		DEFAULT NULL,
  PRIMARY KEY (STUDENT_ID,STUDENT_NAME)
);
COMMIT;
SELECT	*
FROM	JKIM2.Student;