//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.05 at 10:29:17 AM PST 
//


package com.pacsun.customer.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credentials" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}complexType.Credentials" minOccurs="0"/>
 *         &lt;element name="profile" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}complexType.Profile" minOccurs="0"/>
 *         &lt;element name="addresses" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}complexType.Addresses" minOccurs="0"/>
 *         &lt;element name="customer-groups" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}complexType.CustomerGroups" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="customer-no" use="required" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.100" />
 *       &lt;attribute name="mode" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.ImportMode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Customer", namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", propOrder = {
    "credentials",
    "profile",
    "addresses",
    "customerGroups"
})
public class ComplexTypeCustomer {

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected ComplexTypeCredentials credentials;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected ComplexTypeProfile profile;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected ComplexTypeAddresses addresses;
    @XmlElement(name = "customer-groups", namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected ComplexTypeCustomerGroups customerGroups;
    @XmlAttribute(name = "customer-no", required = true)
    protected String customerNo;
    @XmlAttribute(name = "mode")
    protected SimpleTypeImportMode mode;

    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeCredentials }
     *     
     */
    public ComplexTypeCredentials getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeCredentials }
     *     
     */
    public void setCredentials(ComplexTypeCredentials value) {
        this.credentials = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProfile }
     *     
     */
    public ComplexTypeProfile getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProfile }
     *     
     */
    public void setProfile(ComplexTypeProfile value) {
        this.profile = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeAddresses }
     *     
     */
    public ComplexTypeAddresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeAddresses }
     *     
     */
    public void setAddresses(ComplexTypeAddresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the customerGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeCustomerGroups }
     *     
     */
    public ComplexTypeCustomerGroups getCustomerGroups() {
        return customerGroups;
    }

    /**
     * Sets the value of the customerGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeCustomerGroups }
     *     
     */
    public void setCustomerGroups(ComplexTypeCustomerGroups value) {
        this.customerGroups = value;
    }

    /**
     * Gets the value of the customerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * Sets the value of the customerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNo(String value) {
        this.customerNo = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public SimpleTypeImportMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public void setMode(SimpleTypeImportMode value) {
        this.mode = value;
    }

}
