//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.05 at 10:29:17 AM PST 
//


package com.pacsun.customer.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Credentials complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Credentials">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="login" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Login"/>
 *         &lt;element name="password" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}complexType.Password" minOccurs="0"/>
 *         &lt;element name="enabled-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="password-question" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="password-answer" type="{http://www.demandware.com/xml/impex/customer/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Credentials", namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", propOrder = {
    "login",
    "password",
    "enabledFlag",
    "passwordQuestion",
    "passwordAnswer"
})
public class ComplexTypeCredentials {

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", required = true)
    protected String login;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected ComplexTypePassword password;
    @XmlElement(name = "enabled-flag", namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected Boolean enabledFlag;
    @XmlElement(name = "password-question", namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected String passwordQuestion;
    @XmlElement(name = "password-answer", namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31")
    protected String passwordAnswer;

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypePassword }
     *     
     */
    public ComplexTypePassword getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypePassword }
     *     
     */
    public void setPassword(ComplexTypePassword value) {
        this.password = value;
    }

    /**
     * Gets the value of the enabledFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabledFlag() {
        return enabledFlag;
    }

    /**
     * Sets the value of the enabledFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabledFlag(Boolean value) {
        this.enabledFlag = value;
    }

    /**
     * Gets the value of the passwordQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordQuestion() {
        return passwordQuestion;
    }

    /**
     * Sets the value of the passwordQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordQuestion(String value) {
        this.passwordQuestion = value;
    }

    /**
     * Gets the value of the passwordAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordAnswer() {
        return passwordAnswer;
    }

    /**
     * Sets the value of the passwordAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordAnswer(String value) {
        this.passwordAnswer = value;
    }

}
