//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;choice minOccurs="0">
 *           &lt;element name="credit-card" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.CreditCard"/>
 *           &lt;element name="bank-transfer" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.BankTransfer"/>
 *           &lt;element name="bml" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.BillMeLater"/>
 *           &lt;element name="gift-certificate" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.GiftCertificate"/>
 *           &lt;element name="custom-method" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.CustomPaymentMethod"/>
 *         &lt;/choice>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="processor-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="transaction-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="transaction-type" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Payment.TransactionType" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/order/2006-10-31}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Payment", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "creditCard",
    "bankTransfer",
    "bml",
    "giftCertificate",
    "customMethod",
    "amount",
    "processorId",
    "transactionId",
    "transactionType",
    "customAttributes"
})
public class ComplexTypePayment {

    @XmlElement(name = "credit-card", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeCreditCard creditCard;
    @XmlElement(name = "bank-transfer", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeBankTransfer bankTransfer;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeBillMeLater bml;
    @XmlElement(name = "gift-certificate", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeGiftCertificate giftCertificate;
    @XmlElement(name = "custom-method", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeCustomPaymentMethod customMethod;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected BigDecimal amount;
    @XmlElement(name = "processor-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String processorId;
    @XmlElement(name = "transaction-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String transactionId;
    @XmlElement(name = "transaction-type", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypePaymentTransactionType transactionType;
    @XmlElement(name = "custom-attributes", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SharedTypeCustomAttributes customAttributes;

    /**
     * Gets the value of the creditCard property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeCreditCard }
     *     
     */
    public ComplexTypeCreditCard getCreditCard() {
        return creditCard;
    }

    /**
     * Sets the value of the creditCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeCreditCard }
     *     
     */
    public void setCreditCard(ComplexTypeCreditCard value) {
        this.creditCard = value;
    }

    /**
     * Gets the value of the bankTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeBankTransfer }
     *     
     */
    public ComplexTypeBankTransfer getBankTransfer() {
        return bankTransfer;
    }

    /**
     * Sets the value of the bankTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeBankTransfer }
     *     
     */
    public void setBankTransfer(ComplexTypeBankTransfer value) {
        this.bankTransfer = value;
    }

    /**
     * Gets the value of the bml property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeBillMeLater }
     *     
     */
    public ComplexTypeBillMeLater getBml() {
        return bml;
    }

    /**
     * Sets the value of the bml property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeBillMeLater }
     *     
     */
    public void setBml(ComplexTypeBillMeLater value) {
        this.bml = value;
    }

    /**
     * Gets the value of the giftCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeGiftCertificate }
     *     
     */
    public ComplexTypeGiftCertificate getGiftCertificate() {
        return giftCertificate;
    }

    /**
     * Sets the value of the giftCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeGiftCertificate }
     *     
     */
    public void setGiftCertificate(ComplexTypeGiftCertificate value) {
        this.giftCertificate = value;
    }

    /**
     * Gets the value of the customMethod property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeCustomPaymentMethod }
     *     
     */
    public ComplexTypeCustomPaymentMethod getCustomMethod() {
        return customMethod;
    }

    /**
     * Sets the value of the customMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeCustomPaymentMethod }
     *     
     */
    public void setCustomMethod(ComplexTypeCustomPaymentMethod value) {
        this.customMethod = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the processorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessorId() {
        return processorId;
    }

    /**
     * Sets the value of the processorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessorId(String value) {
        this.processorId = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypePaymentTransactionType }
     *     
     */
    public SimpleTypePaymentTransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypePaymentTransactionType }
     *     
     */
    public void setTransactionType(SimpleTypePaymentTransactionType value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

}
