//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Shipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Shipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.ShipmentStatusSet" minOccurs="0"/>
 *         &lt;element name="shipping-method" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="tracking-number" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="shipping-address" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Address" minOccurs="0"/>
 *         &lt;element name="gift" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="gift-message" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.4000" minOccurs="0"/>
 *         &lt;element name="totals" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.ShipmentTotals" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/order/2006-10-31}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="shipment-id" use="required" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Shipment", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "status",
    "shippingMethod",
    "trackingNumber",
    "shippingAddress",
    "gift",
    "giftMessage",
    "totals",
    "customAttributes"
})
public class ComplexTypeShipment {

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeShipmentStatusSet status;
    @XmlElement(name = "shipping-method", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String shippingMethod;
    @XmlElement(name = "tracking-number", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String trackingNumber;
    @XmlElement(name = "shipping-address", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeAddress shippingAddress;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected Boolean gift;
    @XmlElement(name = "gift-message", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String giftMessage;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeShipmentTotals totals;
    @XmlElement(name = "custom-attributes", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SharedTypeCustomAttributes customAttributes;
    @XmlAttribute(name = "shipment-id", required = true)
    protected String shipmentId;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeShipmentStatusSet }
     *     
     */
    public ComplexTypeShipmentStatusSet getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeShipmentStatusSet }
     *     
     */
    public void setStatus(ComplexTypeShipmentStatusSet value) {
        this.status = value;
    }

    /**
     * Gets the value of the shippingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingMethod() {
        return shippingMethod;
    }

    /**
     * Sets the value of the shippingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingMethod(String value) {
        this.shippingMethod = value;
    }

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeAddress }
     *     
     */
    public ComplexTypeAddress getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeAddress }
     *     
     */
    public void setShippingAddress(ComplexTypeAddress value) {
        this.shippingAddress = value;
    }

    /**
     * Gets the value of the gift property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGift() {
        return gift;
    }

    /**
     * Sets the value of the gift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGift(Boolean value) {
        this.gift = value;
    }

    /**
     * Gets the value of the giftMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiftMessage() {
        return giftMessage;
    }

    /**
     * Sets the value of the giftMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiftMessage(String value) {
        this.giftMessage = value;
    }

    /**
     * Gets the value of the totals property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeShipmentTotals }
     *     
     */
    public ComplexTypeShipmentTotals getTotals() {
        return totals;
    }

    /**
     * Sets the value of the totals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeShipmentTotals }
     *     
     */
    public void setTotals(ComplexTypeShipmentTotals value) {
        this.totals = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the shipmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentId(String value) {
        this.shipmentId = value;
    }

}
