//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Total complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Total">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Amounts">
 *       &lt;sequence>
 *         &lt;element name="price-adjustments" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.PriceAdjustments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Total", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "priceAdjustments"
})
public class ComplexTypeTotal
    extends ComplexTypeAmounts
{

    @XmlElement(name = "price-adjustments", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypePriceAdjustments priceAdjustments;

    /**
     * Gets the value of the priceAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypePriceAdjustments }
     *     
     */
    public ComplexTypePriceAdjustments getPriceAdjustments() {
        return priceAdjustments;
    }

    /**
     * Sets the value of the priceAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypePriceAdjustments }
     *     
     */
    public void setPriceAdjustments(ComplexTypePriceAdjustments value) {
        this.priceAdjustments = value;
    }

}
