//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.PriceAdjustment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.PriceAdjustment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.LineItemAmounts">
 *       &lt;sequence>
 *         &lt;element name="promotion-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="campaign-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *           &lt;element name="abtest" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.ABTestSegment" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="coupon-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/order/2006-10-31}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.PriceAdjustment", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "promotionId",
    "campaignId",
    "abtest",
    "couponId",
    "customAttributes"
})
public class ComplexTypePriceAdjustment
    extends ComplexTypeLineItemAmounts
{

    @XmlElement(name = "promotion-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String promotionId;
    @XmlElement(name = "campaign-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String campaignId;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeABTestSegment abtest;
    @XmlElement(name = "coupon-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String couponId;
    @XmlElement(name = "custom-attributes", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SharedTypeCustomAttributes customAttributes;

    /**
     * Gets the value of the promotionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionId() {
        return promotionId;
    }

    /**
     * Sets the value of the promotionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionId(String value) {
        this.promotionId = value;
    }

    /**
     * Gets the value of the campaignId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * Sets the value of the campaignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaignId(String value) {
        this.campaignId = value;
    }

    /**
     * Gets the value of the abtest property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeABTestSegment }
     *     
     */
    public ComplexTypeABTestSegment getAbtest() {
        return abtest;
    }

    /**
     * Sets the value of the abtest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeABTestSegment }
     *     
     */
    public void setAbtest(ComplexTypeABTestSegment value) {
        this.abtest = value;
    }

    /**
     * Gets the value of the couponId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * Sets the value of the couponId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponId(String value) {
        this.couponId = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

}
