//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.LineItemAmounts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.LineItemAmounts">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Amounts">
 *       &lt;sequence>
 *         &lt;element name="base-price" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="lineitem-text" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256"/>
 *         &lt;element name="tax-basis" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.LineItemAmounts", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "basePrice",
    "lineitemText",
    "taxBasis"
})
@XmlSeeAlso({
    ComplexTypeOptionLineItem.class,
    ComplexTypeProductLineItem.class,
    ComplexTypeShippingLineItem.class,
    ComplexTypeGiftCertificateLineItem.class,
    ComplexTypeProductShippingLineItem.class,
    ComplexTypePriceAdjustment.class
})
public class ComplexTypeLineItemAmounts
    extends ComplexTypeAmounts
{

    @XmlElement(name = "base-price", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected BigDecimal basePrice;
    @XmlElement(name = "lineitem-text", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", required = true)
    protected String lineitemText;
    @XmlElement(name = "tax-basis", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected BigDecimal taxBasis;

    /**
     * Gets the value of the basePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBasePrice(BigDecimal value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the lineitemText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineitemText() {
        return lineitemText;
    }

    /**
     * Sets the value of the lineitemText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineitemText(String value) {
        this.lineitemText = value;
    }

    /**
     * Gets the value of the taxBasis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxBasis() {
        return taxBasis;
    }

    /**
     * Sets the value of the taxBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxBasis(BigDecimal value) {
        this.taxBasis = value;
    }

}
