//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.GiftCertificateLineItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.GiftCertificateLineItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.LineItemAmounts">
 *       &lt;sequence>
 *         &lt;element name="gc-merchant-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="giftcertificate-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="recipient-email" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="sender-name" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="recipient-name" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.4000" minOccurs="0"/>
 *         &lt;element name="shipment-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/order/2006-10-31}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.GiftCertificateLineItem", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "gcMerchantId",
    "giftcertificateId",
    "recipientEmail",
    "senderName",
    "recipientName",
    "message",
    "shipmentId",
    "customAttributes"
})
public class ComplexTypeGiftCertificateLineItem
    extends ComplexTypeLineItemAmounts
{

    @XmlElement(name = "gc-merchant-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String gcMerchantId;
    @XmlElement(name = "giftcertificate-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String giftcertificateId;
    @XmlElement(name = "recipient-email", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String recipientEmail;
    @XmlElement(name = "sender-name", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String senderName;
    @XmlElement(name = "recipient-name", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String recipientName;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String message;
    @XmlElement(name = "shipment-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String shipmentId;
    @XmlElement(name = "custom-attributes", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SharedTypeCustomAttributes customAttributes;

    /**
     * Gets the value of the gcMerchantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGcMerchantId() {
        return gcMerchantId;
    }

    /**
     * Sets the value of the gcMerchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGcMerchantId(String value) {
        this.gcMerchantId = value;
    }

    /**
     * Gets the value of the giftcertificateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiftcertificateId() {
        return giftcertificateId;
    }

    /**
     * Sets the value of the giftcertificateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiftcertificateId(String value) {
        this.giftcertificateId = value;
    }

    /**
     * Gets the value of the recipientEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientEmail() {
        return recipientEmail;
    }

    /**
     * Sets the value of the recipientEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientEmail(String value) {
        this.recipientEmail = value;
    }

    /**
     * Gets the value of the senderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * Sets the value of the senderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderName(String value) {
        this.senderName = value;
    }

    /**
     * Gets the value of the recipientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * Sets the value of the recipientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientName(String value) {
        this.recipientName = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the shipmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentId(String value) {
        this.shipmentId = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

}
