//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.OptionLineItems complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.OptionLineItems">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="option-lineitem" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.OptionLineItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.OptionLineItems", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "optionLineitem"
})
public class ComplexTypeOptionLineItems {

    @XmlElement(name = "option-lineitem", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected List<ComplexTypeOptionLineItem> optionLineitem;

    /**
     * Gets the value of the optionLineitem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionLineitem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionLineitem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeOptionLineItem }
     * 
     * 
     */
    public List<ComplexTypeOptionLineItem> getOptionLineitem() {
        if (optionLineitem == null) {
            optionLineitem = new ArrayList<ComplexTypeOptionLineItem>();
        }
        return this.optionLineitem;
    }

}
