//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.ShipmentStatusSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.ShipmentStatusSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shipping-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Shipment.ShippingStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.ShipmentStatusSet", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "shippingStatus"
})
public class ComplexTypeShipmentStatusSet {

    @XmlElement(name = "shipping-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypeShipmentShippingStatus shippingStatus;

    /**
     * Gets the value of the shippingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeShipmentShippingStatus }
     *     
     */
    public SimpleTypeShipmentShippingStatus getShippingStatus() {
        return shippingStatus;
    }

    /**
     * Sets the value of the shippingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeShipmentShippingStatus }
     *     
     */
    public void setShippingStatus(SimpleTypeShipmentShippingStatus value) {
        this.shippingStatus = value;
    }

}
