//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.OrderStatusSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.OrderStatusSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="order-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Order.OrderStatus" minOccurs="0"/>
 *         &lt;element name="shipping-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Order.ShippingStatus" minOccurs="0"/>
 *         &lt;element name="confirmation-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Order.ConfirmationStatus" minOccurs="0"/>
 *         &lt;element name="payment-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Order.PaymentStatus" minOccurs="0"/>
 *         &lt;element name="export-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Order.ExportStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.OrderStatusSet", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "orderStatus",
    "shippingStatus",
    "confirmationStatus",
    "paymentStatus",
    "exportStatus"
})
public class ComplexTypeOrderStatusSet {

    @XmlElement(name = "order-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypeOrderOrderStatus orderStatus;
    @XmlElement(name = "shipping-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypeOrderShippingStatus shippingStatus;
    @XmlElement(name = "confirmation-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypeOrderConfirmationStatus confirmationStatus;
    @XmlElement(name = "payment-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypeOrderPaymentStatus paymentStatus;
    @XmlElement(name = "export-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SimpleTypeOrderExportStatus exportStatus;

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeOrderOrderStatus }
     *     
     */
    public SimpleTypeOrderOrderStatus getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeOrderOrderStatus }
     *     
     */
    public void setOrderStatus(SimpleTypeOrderOrderStatus value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the shippingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeOrderShippingStatus }
     *     
     */
    public SimpleTypeOrderShippingStatus getShippingStatus() {
        return shippingStatus;
    }

    /**
     * Sets the value of the shippingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeOrderShippingStatus }
     *     
     */
    public void setShippingStatus(SimpleTypeOrderShippingStatus value) {
        this.shippingStatus = value;
    }

    /**
     * Gets the value of the confirmationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeOrderConfirmationStatus }
     *     
     */
    public SimpleTypeOrderConfirmationStatus getConfirmationStatus() {
        return confirmationStatus;
    }

    /**
     * Sets the value of the confirmationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeOrderConfirmationStatus }
     *     
     */
    public void setConfirmationStatus(SimpleTypeOrderConfirmationStatus value) {
        this.confirmationStatus = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeOrderPaymentStatus }
     *     
     */
    public SimpleTypeOrderPaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeOrderPaymentStatus }
     *     
     */
    public void setPaymentStatus(SimpleTypeOrderPaymentStatus value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the exportStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeOrderExportStatus }
     *     
     */
    public SimpleTypeOrderExportStatus getExportStatus() {
        return exportStatus;
    }

    /**
     * Sets the value of the exportStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeOrderExportStatus }
     *     
     */
    public void setExportStatus(SimpleTypeOrderExportStatus value) {
        this.exportStatus = value;
    }

}
