//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.ProductShippingLineItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.ProductShippingLineItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.LineItemAmounts">
 *       &lt;sequence>
 *         &lt;element name="quantity" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Quantity"/>
 *         &lt;element name="tax-rate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="type" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.ProductShippingCostType"/>
 *         &lt;element name="price-adjustments" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.PriceAdjustments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.ProductShippingLineItem", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "quantity",
    "taxRate",
    "type",
    "priceAdjustments"
})
public class ComplexTypeProductShippingLineItem
    extends ComplexTypeLineItemAmounts
{

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", required = true)
    protected ComplexTypeQuantity quantity;
    @XmlElement(name = "tax-rate", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected double taxRate;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", required = true)
    protected SimpleTypeProductShippingCostType type;
    @XmlElement(name = "price-adjustments", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypePriceAdjustments priceAdjustments;

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeQuantity }
     *     
     */
    public ComplexTypeQuantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeQuantity }
     *     
     */
    public void setQuantity(ComplexTypeQuantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     */
    public double getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     */
    public void setTaxRate(double value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeProductShippingCostType }
     *     
     */
    public SimpleTypeProductShippingCostType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeProductShippingCostType }
     *     
     */
    public void setType(SimpleTypeProductShippingCostType value) {
        this.type = value;
    }

    /**
     * Gets the value of the priceAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypePriceAdjustments }
     *     
     */
    public ComplexTypePriceAdjustments getPriceAdjustments() {
        return priceAdjustments;
    }

    /**
     * Sets the value of the priceAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypePriceAdjustments }
     *     
     */
    public void setPriceAdjustments(ComplexTypePriceAdjustments value) {
        this.priceAdjustments = value;
    }

}
