//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.ShipmentTotals complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.ShipmentTotals">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchandize-total" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Total" minOccurs="0"/>
 *         &lt;element name="adjusted-merchandize-total" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Total" minOccurs="0"/>
 *         &lt;element name="shipping-total" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Total" minOccurs="0"/>
 *         &lt;element name="adjusted-shipping-total" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Total" minOccurs="0"/>
 *         &lt;element name="shipment-total" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Total" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.ShipmentTotals", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "merchandizeTotal",
    "adjustedMerchandizeTotal",
    "shippingTotal",
    "adjustedShippingTotal",
    "shipmentTotal"
})
public class ComplexTypeShipmentTotals {

    @XmlElement(name = "merchandize-total", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeTotal merchandizeTotal;
    @XmlElement(name = "adjusted-merchandize-total", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeTotal adjustedMerchandizeTotal;
    @XmlElement(name = "shipping-total", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeTotal shippingTotal;
    @XmlElement(name = "adjusted-shipping-total", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeTotal adjustedShippingTotal;
    @XmlElement(name = "shipment-total", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeTotal shipmentTotal;

    /**
     * Gets the value of the merchandizeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public ComplexTypeTotal getMerchandizeTotal() {
        return merchandizeTotal;
    }

    /**
     * Sets the value of the merchandizeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public void setMerchandizeTotal(ComplexTypeTotal value) {
        this.merchandizeTotal = value;
    }

    /**
     * Gets the value of the adjustedMerchandizeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public ComplexTypeTotal getAdjustedMerchandizeTotal() {
        return adjustedMerchandizeTotal;
    }

    /**
     * Sets the value of the adjustedMerchandizeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public void setAdjustedMerchandizeTotal(ComplexTypeTotal value) {
        this.adjustedMerchandizeTotal = value;
    }

    /**
     * Gets the value of the shippingTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public ComplexTypeTotal getShippingTotal() {
        return shippingTotal;
    }

    /**
     * Sets the value of the shippingTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public void setShippingTotal(ComplexTypeTotal value) {
        this.shippingTotal = value;
    }

    /**
     * Gets the value of the adjustedShippingTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public ComplexTypeTotal getAdjustedShippingTotal() {
        return adjustedShippingTotal;
    }

    /**
     * Sets the value of the adjustedShippingTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public void setAdjustedShippingTotal(ComplexTypeTotal value) {
        this.adjustedShippingTotal = value;
    }

    /**
     * Gets the value of the shipmentTotal property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public ComplexTypeTotal getShipmentTotal() {
        return shipmentTotal;
    }

    /**
     * Sets the value of the shipmentTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeTotal }
     *     
     */
    public void setShipmentTotal(ComplexTypeTotal value) {
        this.shipmentTotal = value;
    }

}
