//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for complexType.Order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="order-date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="created-by" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="original-order-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Currency"/>
 *         &lt;element name="customer-locale" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="source-code" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.SourceCode" minOccurs="0"/>
 *         &lt;element name="affiliate-partner-name" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="affiliate-partner-id" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="invoice-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="customer" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Customer" minOccurs="0"/>
 *         &lt;element name="customer-order-reference" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.OrderStatusSet" minOccurs="0"/>
 *         &lt;element name="replace-code" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="replace-description" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.4000" minOccurs="0"/>
 *         &lt;element name="replacement-order-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="replaced-order-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="current-order-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="cancel-code" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="cancel-description" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.4000" minOccurs="0"/>
 *         &lt;element name="product-lineitems" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.ProductLineItems" minOccurs="0"/>
 *         &lt;element name="giftcertificate-lineitems" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.GiftCertificateLineItems" minOccurs="0"/>
 *         &lt;element name="shipping-lineitems" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.ShippingLineItems" minOccurs="0"/>
 *         &lt;element name="shipments" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Shipments" minOccurs="0"/>
 *         &lt;element name="totals" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.OrderTotals" minOccurs="0"/>
 *         &lt;element name="payments" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Payments" minOccurs="0"/>
 *         &lt;element name="remoteHost" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.40" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Notes" minOccurs="0"/>
 *         &lt;element name="external-order-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="external-order-status" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="external-order-text" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/order/2006-10-31}sharedType.CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="order-no" use="required" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Order", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "orderDate",
    "createdBy",
    "originalOrderNo",
    "currency",
    "customerLocale",
    "sourceCode",
    "affiliatePartnerName",
    "affiliatePartnerId",
    "invoiceNo",
    "customer",
    "customerOrderReference",
    "status",
    "replaceCode",
    "replaceDescription",
    "replacementOrderNo",
    "replacedOrderNo",
    "currentOrderNo",
    "cancelCode",
    "cancelDescription",
    "productLineitems",
    "giftcertificateLineitems",
    "shippingLineitems",
    "shipments",
    "totals",
    "payments",
    "remoteHost",
    "notes",
    "externalOrderNo",
    "externalOrderStatus",
    "externalOrderText",
    "customAttributes"
})
public class ComplexTypeOrder {

    @XmlElement(name = "order-date", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar orderDate;
    @XmlElement(name = "created-by", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String createdBy;
    @XmlElement(name = "original-order-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String originalOrderNo;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", required = true)
    protected String currency;
    @XmlElement(name = "customer-locale", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String customerLocale;
    @XmlElement(name = "source-code", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeSourceCode sourceCode;
    @XmlElement(name = "affiliate-partner-name", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String affiliatePartnerName;
    @XmlElement(name = "affiliate-partner-id", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String affiliatePartnerId;
    @XmlElement(name = "invoice-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String invoiceNo;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeCustomer customer;
    @XmlElement(name = "customer-order-reference", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String customerOrderReference;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeOrderStatusSet status;
    @XmlElement(name = "replace-code", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String replaceCode;
    @XmlElement(name = "replace-description", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String replaceDescription;
    @XmlElement(name = "replacement-order-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String replacementOrderNo;
    @XmlElement(name = "replaced-order-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String replacedOrderNo;
    @XmlElement(name = "current-order-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String currentOrderNo;
    @XmlElement(name = "cancel-code", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String cancelCode;
    @XmlElement(name = "cancel-description", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String cancelDescription;
    @XmlElement(name = "product-lineitems", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeProductLineItems productLineitems;
    @XmlElement(name = "giftcertificate-lineitems", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeGiftCertificateLineItems giftcertificateLineitems;
    @XmlElement(name = "shipping-lineitems", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeShippingLineItems shippingLineitems;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeShipments shipments;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeOrderTotals totals;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypePayments payments;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String remoteHost;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeNotes notes;
    @XmlElement(name = "external-order-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String externalOrderNo;
    @XmlElement(name = "external-order-status", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String externalOrderStatus;
    @XmlElement(name = "external-order-text", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String externalOrderText;
    @XmlElement(name = "custom-attributes", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected SharedTypeCustomAttributes customAttributes;
    @XmlAttribute(name = "order-no", required = true)
    protected String orderNo;

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDate(XMLGregorianCalendar value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the originalOrderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalOrderNo() {
        return originalOrderNo;
    }

    /**
     * Sets the value of the originalOrderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalOrderNo(String value) {
        this.originalOrderNo = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the customerLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerLocale() {
        return customerLocale;
    }

    /**
     * Sets the value of the customerLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerLocale(String value) {
        this.customerLocale = value;
    }

    /**
     * Gets the value of the sourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeSourceCode }
     *     
     */
    public ComplexTypeSourceCode getSourceCode() {
        return sourceCode;
    }

    /**
     * Sets the value of the sourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeSourceCode }
     *     
     */
    public void setSourceCode(ComplexTypeSourceCode value) {
        this.sourceCode = value;
    }

    /**
     * Gets the value of the affiliatePartnerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliatePartnerName() {
        return affiliatePartnerName;
    }

    /**
     * Sets the value of the affiliatePartnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliatePartnerName(String value) {
        this.affiliatePartnerName = value;
    }

    /**
     * Gets the value of the affiliatePartnerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliatePartnerId() {
        return affiliatePartnerId;
    }

    /**
     * Sets the value of the affiliatePartnerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliatePartnerId(String value) {
        this.affiliatePartnerId = value;
    }

    /**
     * Gets the value of the invoiceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * Sets the value of the invoiceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNo(String value) {
        this.invoiceNo = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeCustomer }
     *     
     */
    public ComplexTypeCustomer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeCustomer }
     *     
     */
    public void setCustomer(ComplexTypeCustomer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerOrderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerOrderReference() {
        return customerOrderReference;
    }

    /**
     * Sets the value of the customerOrderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerOrderReference(String value) {
        this.customerOrderReference = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeOrderStatusSet }
     *     
     */
    public ComplexTypeOrderStatusSet getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeOrderStatusSet }
     *     
     */
    public void setStatus(ComplexTypeOrderStatusSet value) {
        this.status = value;
    }

    /**
     * Gets the value of the replaceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaceCode() {
        return replaceCode;
    }

    /**
     * Sets the value of the replaceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaceCode(String value) {
        this.replaceCode = value;
    }

    /**
     * Gets the value of the replaceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaceDescription() {
        return replaceDescription;
    }

    /**
     * Sets the value of the replaceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaceDescription(String value) {
        this.replaceDescription = value;
    }

    /**
     * Gets the value of the replacementOrderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacementOrderNo() {
        return replacementOrderNo;
    }

    /**
     * Sets the value of the replacementOrderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacementOrderNo(String value) {
        this.replacementOrderNo = value;
    }

    /**
     * Gets the value of the replacedOrderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacedOrderNo() {
        return replacedOrderNo;
    }

    /**
     * Sets the value of the replacedOrderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacedOrderNo(String value) {
        this.replacedOrderNo = value;
    }

    /**
     * Gets the value of the currentOrderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentOrderNo() {
        return currentOrderNo;
    }

    /**
     * Sets the value of the currentOrderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentOrderNo(String value) {
        this.currentOrderNo = value;
    }

    /**
     * Gets the value of the cancelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelCode() {
        return cancelCode;
    }

    /**
     * Sets the value of the cancelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelCode(String value) {
        this.cancelCode = value;
    }

    /**
     * Gets the value of the cancelDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelDescription() {
        return cancelDescription;
    }

    /**
     * Sets the value of the cancelDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelDescription(String value) {
        this.cancelDescription = value;
    }

    /**
     * Gets the value of the productLineitems property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductLineItems }
     *     
     */
    public ComplexTypeProductLineItems getProductLineitems() {
        return productLineitems;
    }

    /**
     * Sets the value of the productLineitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductLineItems }
     *     
     */
    public void setProductLineitems(ComplexTypeProductLineItems value) {
        this.productLineitems = value;
    }

    /**
     * Gets the value of the giftcertificateLineitems property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeGiftCertificateLineItems }
     *     
     */
    public ComplexTypeGiftCertificateLineItems getGiftcertificateLineitems() {
        return giftcertificateLineitems;
    }

    /**
     * Sets the value of the giftcertificateLineitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeGiftCertificateLineItems }
     *     
     */
    public void setGiftcertificateLineitems(ComplexTypeGiftCertificateLineItems value) {
        this.giftcertificateLineitems = value;
    }

    /**
     * Gets the value of the shippingLineitems property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeShippingLineItems }
     *     
     */
    public ComplexTypeShippingLineItems getShippingLineitems() {
        return shippingLineitems;
    }

    /**
     * Sets the value of the shippingLineitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeShippingLineItems }
     *     
     */
    public void setShippingLineitems(ComplexTypeShippingLineItems value) {
        this.shippingLineitems = value;
    }

    /**
     * Gets the value of the shipments property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeShipments }
     *     
     */
    public ComplexTypeShipments getShipments() {
        return shipments;
    }

    /**
     * Sets the value of the shipments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeShipments }
     *     
     */
    public void setShipments(ComplexTypeShipments value) {
        this.shipments = value;
    }

    /**
     * Gets the value of the totals property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeOrderTotals }
     *     
     */
    public ComplexTypeOrderTotals getTotals() {
        return totals;
    }

    /**
     * Sets the value of the totals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeOrderTotals }
     *     
     */
    public void setTotals(ComplexTypeOrderTotals value) {
        this.totals = value;
    }

    /**
     * Gets the value of the payments property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypePayments }
     *     
     */
    public ComplexTypePayments getPayments() {
        return payments;
    }

    /**
     * Sets the value of the payments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypePayments }
     *     
     */
    public void setPayments(ComplexTypePayments value) {
        this.payments = value;
    }

    /**
     * Gets the value of the remoteHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteHost() {
        return remoteHost;
    }

    /**
     * Sets the value of the remoteHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteHost(String value) {
        this.remoteHost = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeNotes }
     *     
     */
    public ComplexTypeNotes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeNotes }
     *     
     */
    public void setNotes(ComplexTypeNotes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the externalOrderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalOrderNo() {
        return externalOrderNo;
    }

    /**
     * Sets the value of the externalOrderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalOrderNo(String value) {
        this.externalOrderNo = value;
    }

    /**
     * Gets the value of the externalOrderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalOrderStatus() {
        return externalOrderStatus;
    }

    /**
     * Sets the value of the externalOrderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalOrderStatus(String value) {
        this.externalOrderStatus = value;
    }

    /**
     * Gets the value of the externalOrderText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalOrderText() {
        return externalOrderText;
    }

    /**
     * Sets the value of the externalOrderText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalOrderText(String value) {
        this.externalOrderText = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public SharedTypeCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeCustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

}
