//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customer-no" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.100" minOccurs="0"/>
 *         &lt;element name="customer-name" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="customer-email" type="{http://www.demandware.com/xml/impex/order/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="billing-address" type="{http://www.demandware.com/xml/impex/order/2006-10-31}complexType.Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Customer", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", propOrder = {
    "customerNo",
    "customerName",
    "customerEmail",
    "billingAddress"
})
public class ComplexTypeCustomer {

    @XmlElement(name = "customer-no", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String customerNo;
    @XmlElement(name = "customer-name", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String customerName;
    @XmlElement(name = "customer-email", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected String customerEmail;
    @XmlElement(name = "billing-address", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
    protected ComplexTypeAddress billingAddress;

    /**
     * Gets the value of the customerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * Sets the value of the customerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNo(String value) {
        this.customerNo = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the value of the customerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmail(String value) {
        this.customerEmail = value;
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeAddress }
     *     
     */
    public ComplexTypeAddress getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeAddress }
     *     
     */
    public void setBillingAddress(ComplexTypeAddress value) {
        this.billingAddress = value;
    }

}
