//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pacsun.dworder.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Order_QNAME = new QName("http://www.demandware.com/xml/impex/order/2006-10-31", "order");
    private final static QName _SharedTypeCustomAttributeValue_QNAME = new QName("http://www.demandware.com/xml/impex/order/2006-10-31", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pacsun.dworder.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Orders }
     * 
     */
    public Orders createOrders() {
        return new Orders();
    }

    /**
     * Create an instance of {@link ComplexTypeOrder }
     * 
     */
    public ComplexTypeOrder createComplexTypeOrder() {
        return new ComplexTypeOrder();
    }

    /**
     * Create an instance of {@link ComplexTypePayments }
     * 
     */
    public ComplexTypePayments createComplexTypePayments() {
        return new ComplexTypePayments();
    }

    /**
     * Create an instance of {@link ComplexTypeBundledProductLineItem }
     * 
     */
    public ComplexTypeBundledProductLineItem createComplexTypeBundledProductLineItem() {
        return new ComplexTypeBundledProductLineItem();
    }

    /**
     * Create an instance of {@link ComplexTypeOrderStatusSet }
     * 
     */
    public ComplexTypeOrderStatusSet createComplexTypeOrderStatusSet() {
        return new ComplexTypeOrderStatusSet();
    }

    /**
     * Create an instance of {@link ComplexTypeOptionLineItem }
     * 
     */
    public ComplexTypeOptionLineItem createComplexTypeOptionLineItem() {
        return new ComplexTypeOptionLineItem();
    }

    /**
     * Create an instance of {@link SimpleTypeAmount }
     * 
     */
    public SimpleTypeAmount createSimpleTypeAmount() {
        return new SimpleTypeAmount();
    }

    /**
     * Create an instance of {@link ComplexTypeShipment }
     * 
     */
    public ComplexTypeShipment createComplexTypeShipment() {
        return new ComplexTypeShipment();
    }

    /**
     * Create an instance of {@link ComplexTypeAddress }
     * 
     */
    public ComplexTypeAddress createComplexTypeAddress() {
        return new ComplexTypeAddress();
    }

    /**
     * Create an instance of {@link ComplexTypeOrderDetails }
     * 
     */
    public ComplexTypeOrderDetails createComplexTypeOrderDetails() {
        return new ComplexTypeOrderDetails();
    }

    /**
     * Create an instance of {@link ComplexTypeProductLineItem }
     * 
     */
    public ComplexTypeProductLineItem createComplexTypeProductLineItem() {
        return new ComplexTypeProductLineItem();
    }

    /**
     * Create an instance of {@link ComplexTypeOptionLineItems }
     * 
     */
    public ComplexTypeOptionLineItems createComplexTypeOptionLineItems() {
        return new ComplexTypeOptionLineItems();
    }

    /**
     * Create an instance of {@link ComplexTypeAmounts }
     * 
     */
    public ComplexTypeAmounts createComplexTypeAmounts() {
        return new ComplexTypeAmounts();
    }

    /**
     * Create an instance of {@link ComplexTypeSourceCode }
     * 
     */
    public ComplexTypeSourceCode createComplexTypeSourceCode() {
        return new ComplexTypeSourceCode();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomPaymentMethod }
     * 
     */
    public ComplexTypeCustomPaymentMethod createComplexTypeCustomPaymentMethod() {
        return new ComplexTypeCustomPaymentMethod();
    }

    /**
     * Create an instance of {@link ComplexTypeGiftCertificate }
     * 
     */
    public ComplexTypeGiftCertificate createComplexTypeGiftCertificate() {
        return new ComplexTypeGiftCertificate();
    }

    /**
     * Create an instance of {@link ComplexTypeProductLineItems }
     * 
     */
    public ComplexTypeProductLineItems createComplexTypeProductLineItems() {
        return new ComplexTypeProductLineItems();
    }

    /**
     * Create an instance of {@link ComplexTypeShipments }
     * 
     */
    public ComplexTypeShipments createComplexTypeShipments() {
        return new ComplexTypeShipments();
    }

    /**
     * Create an instance of {@link ComplexTypeQuantity }
     * 
     */
    public ComplexTypeQuantity createComplexTypeQuantity() {
        return new ComplexTypeQuantity();
    }

    /**
     * Create an instance of {@link ComplexTypeShippingLineItems }
     * 
     */
    public ComplexTypeShippingLineItems createComplexTypeShippingLineItems() {
        return new ComplexTypeShippingLineItems();
    }

    /**
     * Create an instance of {@link ComplexTypeShipmentTotals }
     * 
     */
    public ComplexTypeShipmentTotals createComplexTypeShipmentTotals() {
        return new ComplexTypeShipmentTotals();
    }

    /**
     * Create an instance of {@link ComplexTypeBankTransfer }
     * 
     */
    public ComplexTypeBankTransfer createComplexTypeBankTransfer() {
        return new ComplexTypeBankTransfer();
    }

    /**
     * Create an instance of {@link ComplexTypeGiftCertificateLineItems }
     * 
     */
    public ComplexTypeGiftCertificateLineItems createComplexTypeGiftCertificateLineItems() {
        return new ComplexTypeGiftCertificateLineItems();
    }

    /**
     * Create an instance of {@link ComplexTypeShippingLineItem }
     * 
     */
    public ComplexTypeShippingLineItem createComplexTypeShippingLineItem() {
        return new ComplexTypeShippingLineItem();
    }

    /**
     * Create an instance of {@link ComplexTypeNotes }
     * 
     */
    public ComplexTypeNotes createComplexTypeNotes() {
        return new ComplexTypeNotes();
    }

    /**
     * Create an instance of {@link ComplexTypeTotal }
     * 
     */
    public ComplexTypeTotal createComplexTypeTotal() {
        return new ComplexTypeTotal();
    }

    /**
     * Create an instance of {@link ComplexTypeABTestSegment }
     * 
     */
    public ComplexTypeABTestSegment createComplexTypeABTestSegment() {
        return new ComplexTypeABTestSegment();
    }

    /**
     * Create an instance of {@link ComplexTypeGiftCertificateLineItem }
     * 
     */
    public ComplexTypeGiftCertificateLineItem createComplexTypeGiftCertificateLineItem() {
        return new ComplexTypeGiftCertificateLineItem();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttributes }
     * 
     */
    public SharedTypeCustomAttributes createSharedTypeCustomAttributes() {
        return new SharedTypeCustomAttributes();
    }

    /**
     * Create an instance of {@link ComplexTypePayment }
     * 
     */
    public ComplexTypePayment createComplexTypePayment() {
        return new ComplexTypePayment();
    }

    /**
     * Create an instance of {@link ComplexTypeProductShippingLineItem }
     * 
     */
    public ComplexTypeProductShippingLineItem createComplexTypeProductShippingLineItem() {
        return new ComplexTypeProductShippingLineItem();
    }

    /**
     * Create an instance of {@link ComplexTypeCreditCard }
     * 
     */
    public ComplexTypeCreditCard createComplexTypeCreditCard() {
        return new ComplexTypeCreditCard();
    }

    /**
     * Create an instance of {@link ComplexTypeCustomer }
     * 
     */
    public ComplexTypeCustomer createComplexTypeCustomer() {
        return new ComplexTypeCustomer();
    }

    /**
     * Create an instance of {@link ComplexTypeBundledProductLineItems }
     * 
     */
    public ComplexTypeBundledProductLineItems createComplexTypeBundledProductLineItems() {
        return new ComplexTypeBundledProductLineItems();
    }

    /**
     * Create an instance of {@link ComplexTypeNote }
     * 
     */
    public ComplexTypeNote createComplexTypeNote() {
        return new ComplexTypeNote();
    }

    /**
     * Create an instance of {@link ComplexTypeOrderTotals }
     * 
     */
    public ComplexTypeOrderTotals createComplexTypeOrderTotals() {
        return new ComplexTypeOrderTotals();
    }

    /**
     * Create an instance of {@link ComplexTypeLineItemAmounts }
     * 
     */
    public ComplexTypeLineItemAmounts createComplexTypeLineItemAmounts() {
        return new ComplexTypeLineItemAmounts();
    }

    /**
     * Create an instance of {@link SharedTypeCustomAttribute }
     * 
     */
    public SharedTypeCustomAttribute createSharedTypeCustomAttribute() {
        return new SharedTypeCustomAttribute();
    }

    /**
     * Create an instance of {@link ComplexTypeBillMeLater }
     * 
     */
    public ComplexTypeBillMeLater createComplexTypeBillMeLater() {
        return new ComplexTypeBillMeLater();
    }

    /**
     * Create an instance of {@link ComplexTypeShipmentStatusSet }
     * 
     */
    public ComplexTypeShipmentStatusSet createComplexTypeShipmentStatusSet() {
        return new ComplexTypeShipmentStatusSet();
    }

    /**
     * Create an instance of {@link ComplexTypePriceAdjustments }
     * 
     */
    public ComplexTypePriceAdjustments createComplexTypePriceAdjustments() {
        return new ComplexTypePriceAdjustments();
    }

    /**
     * Create an instance of {@link ComplexTypePriceAdjustment }
     * 
     */
    public ComplexTypePriceAdjustment createComplexTypePriceAdjustment() {
        return new ComplexTypePriceAdjustment();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexTypeOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", name = "order")
    public JAXBElement<ComplexTypeOrder> createOrder(ComplexTypeOrder value) {
        return new JAXBElement<ComplexTypeOrder>(_Order_QNAME, ComplexTypeOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.demandware.com/xml/impex/order/2006-10-31", name = "value", scope = SharedTypeCustomAttribute.class)
    public JAXBElement<String> createSharedTypeCustomAttributeValue(String value) {
        return new JAXBElement<String>(_SharedTypeCustomAttributeValue_QNAME, String.class, SharedTypeCustomAttribute.class, value);
    }

}
