//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:59:57 PM PDT 
//


package com.pacsun.dworder.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleType.Payment.TransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="simpleType.Payment.TransactionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AUTH"/>
 *     &lt;enumeration value="AUTH_REVERSAL"/>
 *     &lt;enumeration value="CAPTURE"/>
 *     &lt;enumeration value="CREDIT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "simpleType.Payment.TransactionType", namespace = "http://www.demandware.com/xml/impex/order/2006-10-31")
@XmlEnum
public enum SimpleTypePaymentTransactionType {

    AUTH,
    AUTH_REVERSAL,
    CAPTURE,
    CREDIT;

    public String value() {
        return name();
    }

    public static SimpleTypePaymentTransactionType fromValue(String v) {
        return valueOf(v);
    }

}
