DROP TABLE JKIM2.JKORDHDR;
CREATE TABLE JKIM2.JKORDHDR (
	OHORD	INTEGER,
	OHRCST	CHAR(1),
	OHCST	INTEGER,
	OHORDT	DATE,
	OHSTS   CHAR(1),
	PRIMARY KEY(OHORD)
);
COMMIT;
SELECT * FROM JKIM2.JKORDHDR;


DROP TABLE JKIM2.JKORDDTL;
CREATE TABLE JKIM2.JKORDDTL (
	ODORD	INTEGER,
	ODLINE	INTEGER,
	ODITEM	VARCHAR(15),
	ODIDSC	VARCHAR(40),
	ODUPRC	DECIMAL(11,2),
	PRIMARY KEY(ODORD)
);
COMMIT;
SELECT * FROM JKIM2.JKORDDTL;