//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 10:11:34 AM PST 
//


package com.pacsun.catalog.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Deprecated please use the elements variation-attribute (complexType.VariationAttribute) or shared-variation-attribute (complexType.Product.VariationAttribute.Reference).
 * 
 * <p>Java class for complexType.Product.Variations.Attributes.Attribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.Variations.Attributes.Attribute">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.AttributeReference">
 *       &lt;sequence>
 *         &lt;element name="values" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Variations.Attributes.Attribute.Values" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.Variations.Attributes.Attribute", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", propOrder = {
    "values"
})
public class ComplexTypeProductVariationsAttributesAttribute
    extends ComplexTypeAttributeReference
{

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductVariationsAttributesAttributeValues values;

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductVariationsAttributesAttributeValues }
     *     
     */
    public ComplexTypeProductVariationsAttributesAttributeValues getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductVariationsAttributesAttributeValues }
     *     
     */
    public void setValues(ComplexTypeProductVariationsAttributesAttributeValues value) {
        this.values = value;
    }

}
