//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 10:11:34 AM PST 
//


package com.pacsun.catalog.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Product.Variations.Attributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.Variations.Attributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="attribute" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Variations.Attributes.Attribute"/>
 *         &lt;element name="variation-attribute" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.VariationAttribute"/>
 *         &lt;element name="shared-variation-attribute" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.VariationAttribute.Reference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.Variations.Attributes", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", propOrder = {
    "attributeOrVariationAttributeOrSharedVariationAttribute"
})
public class ComplexTypeProductVariationsAttributes {

    @XmlElements({
        @XmlElement(name = "attribute", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", type = ComplexTypeProductVariationsAttributesAttribute.class),
        @XmlElement(name = "variation-attribute", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", type = ComplexTypeVariationAttribute.class),
        @XmlElement(name = "shared-variation-attribute", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", type = ComplexTypeProductVariationAttributeReference.class)
    })
    protected List<Object> attributeOrVariationAttributeOrSharedVariationAttribute;

    /**
     * Gets the value of the attributeOrVariationAttributeOrSharedVariationAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrVariationAttributeOrSharedVariationAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeOrVariationAttributeOrSharedVariationAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexTypeProductVariationsAttributesAttribute }
     * {@link ComplexTypeVariationAttribute }
     * {@link ComplexTypeProductVariationAttributeReference }
     * 
     * 
     */
    public List<Object> getAttributeOrVariationAttributeOrSharedVariationAttribute() {
        if (attributeOrVariationAttributeOrSharedVariationAttribute == null) {
            attributeOrVariationAttributeOrSharedVariationAttribute = new ArrayList<Object>();
        }
        return this.attributeOrVariationAttributeOrSharedVariationAttribute;
    }

}
