//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 10:11:34 AM PST 
//


package com.pacsun.catalog.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Product.Variations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product.Variations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributes" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Variations.Attributes" minOccurs="0"/>
 *         &lt;element name="variants" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Variations.Variants" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product.Variations", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", propOrder = {
    "attributes",
    "variants"
})
public class ComplexTypeProductVariations {

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductVariationsAttributes attributes;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductVariationsVariants variants;

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductVariationsAttributes }
     *     
     */
    public ComplexTypeProductVariationsAttributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductVariationsAttributes }
     *     
     */
    public void setAttributes(ComplexTypeProductVariationsAttributes value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the variants property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductVariationsVariants }
     *     
     */
    public ComplexTypeProductVariationsVariants getVariants() {
        return variants;
    }

    /**
     * Sets the value of the variants property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductVariationsVariants }
     *     
     */
    public void setVariants(ComplexTypeProductVariationsVariants value) {
        this.variants = value;
    }

}
