//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 10:11:34 AM PST 
//


package com.pacsun.catalog.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for complexType.Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complexType.Product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ean" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="upc" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="unit" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="min-order-quantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="step-quantity" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="display-name" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="short-description" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="long-description" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.LocalizedText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="online-flag" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificBoolean" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="online-from" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificDateTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="online-to" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificDateTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="available-flag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="searchable-flag" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificBoolean" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="images" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Images" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="thumbnail" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="template" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="tax-class-id" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.256" minOccurs="0"/>
 *         &lt;element name="brand" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="manufacturer-name" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="manufacturer-sku" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.String.256" minOccurs="0"/>
 *         &lt;element name="search-placement" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificInt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="search-rank" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificInt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sitemap-included-flag" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificBoolean" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sitemap-changefrequency" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificSiteMapChangeFrequency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sitemap-priority" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificSiteMapPriority" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="page-attributes" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.PageAttributes" minOccurs="0"/>
 *         &lt;element name="custom-attributes" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}sharedType.SiteSpecificCustomAttributes" minOccurs="0"/>
 *         &lt;element name="bundled-products" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.BundledProducts" minOccurs="0"/>
 *         &lt;element name="retail-set-products" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.RetailSetProducts" minOccurs="0"/>
 *         &lt;element name="product-set-products" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.ProductSetProducts" minOccurs="0"/>
 *         &lt;element name="options" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Options" minOccurs="0"/>
 *         &lt;element name="variations" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.Variations" minOccurs="0"/>
 *         &lt;element name="product-links" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.ProductLinks" minOccurs="0"/>
 *         &lt;element name="category-links" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.CategoryLinks" minOccurs="0"/>
 *         &lt;element name="classification-category" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}complexType.Product.ClassificationCategory" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mode" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.ImportMode" />
 *       &lt;attribute name="product-id" use="required" type="{http://www.demandware.com/xml/impex/catalog/2006-10-31}simpleType.Generic.NonEmptyString.100" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexType.Product", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", propOrder = {
    "ean",
    "upc",
    "unit",
    "minOrderQuantity",
    "stepQuantity",
    "displayName",
    "shortDescription",
    "longDescription",
    "onlineFlag",
    "onlineFrom",
    "onlineTo",
    "availableFlag",
    "searchableFlag",
    "images",
    "image",
    "thumbnail",
    "template",
    "taxClassId",
    "brand",
    "manufacturerName",
    "manufacturerSku",
    "searchPlacement",
    "searchRank",
    "sitemapIncludedFlag",
    "sitemapChangefrequency",
    "sitemapPriority",
    "pageAttributes",
    "customAttributes",
    "bundledProducts",
    "retailSetProducts",
    "productSetProducts",
    "options",
    "variations",
    "productLinks",
    "categoryLinks",
    "classificationCategory"
})
public class ComplexTypeProduct {

    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String ean;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String upc;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String unit;
    @XmlElement(name = "min-order-quantity", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected BigDecimal minOrderQuantity;
    @XmlElement(name = "step-quantity", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected BigDecimal stepQuantity;
    @XmlElement(name = "display-name", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected List<SharedTypeLocalizedString> displayName;
    @XmlElement(name = "short-description", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected List<SharedTypeLocalizedText> shortDescription;
    @XmlElement(name = "long-description", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected List<SharedTypeLocalizedText> longDescription;
    @XmlElement(name = "online-flag", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected List<SharedTypeSiteSpecificBoolean> onlineFlag;
    @XmlElement(name = "online-from", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificDateTime> onlineFrom;
    @XmlElement(name = "online-to", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificDateTime> onlineTo;
    @XmlElement(name = "available-flag", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected Boolean availableFlag;
    @XmlElement(name = "searchable-flag", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected List<SharedTypeSiteSpecificBoolean> searchableFlag;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductImages images;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String image;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String thumbnail;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String template;
    @XmlElement(name = "tax-class-id", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String taxClassId;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String brand;
    @XmlElement(name = "manufacturer-name", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String manufacturerName;
    @XmlElement(name = "manufacturer-sku", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected String manufacturerSku;
    @XmlElement(name = "search-placement", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificInt> searchPlacement;
    @XmlElement(name = "search-rank", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificInt> searchRank;
    @XmlElement(name = "sitemap-included-flag", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificBoolean> sitemapIncludedFlag;
    @XmlElement(name = "sitemap-changefrequency", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificSiteMapChangeFrequency> sitemapChangefrequency;
    @XmlElement(name = "sitemap-priority", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31", nillable = true)
    protected List<SharedTypeSiteSpecificSiteMapPriority> sitemapPriority;
    @XmlElement(name = "page-attributes", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypePageAttributes pageAttributes;
    @XmlElement(name = "custom-attributes", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected SharedTypeSiteSpecificCustomAttributes customAttributes;
    @XmlElement(name = "bundled-products", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductBundledProducts bundledProducts;
    @XmlElement(name = "retail-set-products", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductRetailSetProducts retailSetProducts;
    @XmlElement(name = "product-set-products", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductProductSetProducts productSetProducts;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductOptions options;
    @XmlElement(namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductVariations variations;
    @XmlElement(name = "product-links", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductProductLinks productLinks;
    @XmlElement(name = "category-links", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductCategoryLinks categoryLinks;
    @XmlElement(name = "classification-category", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
    protected ComplexTypeProductClassificationCategory classificationCategory;
    @XmlAttribute(name = "mode")
    protected SimpleTypeImportMode mode;
    @XmlAttribute(name = "product-id", required = true)
    protected String productId;

    /**
     * Gets the value of the ean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEan() {
        return ean;
    }

    /**
     * Sets the value of the ean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEan(String value) {
        this.ean = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpc() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpc(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the minOrderQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinOrderQuantity() {
        return minOrderQuantity;
    }

    /**
     * Sets the value of the minOrderQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinOrderQuantity(BigDecimal value) {
        this.minOrderQuantity = value;
    }

    /**
     * Gets the value of the stepQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStepQuantity() {
        return stepQuantity;
    }

    /**
     * Sets the value of the stepQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStepQuantity(BigDecimal value) {
        this.stepQuantity = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedString }
     * 
     * 
     */
    public List<SharedTypeLocalizedString> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<SharedTypeLocalizedString>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shortDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShortDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedText }
     * 
     * 
     */
    public List<SharedTypeLocalizedText> getShortDescription() {
        if (shortDescription == null) {
            shortDescription = new ArrayList<SharedTypeLocalizedText>();
        }
        return this.shortDescription;
    }

    /**
     * Gets the value of the longDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLongDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeLocalizedText }
     * 
     * 
     */
    public List<SharedTypeLocalizedText> getLongDescription() {
        if (longDescription == null) {
            longDescription = new ArrayList<SharedTypeLocalizedText>();
        }
        return this.longDescription;
    }

    /**
     * Gets the value of the onlineFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onlineFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnlineFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificBoolean }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificBoolean> getOnlineFlag() {
        if (onlineFlag == null) {
            onlineFlag = new ArrayList<SharedTypeSiteSpecificBoolean>();
        }
        return this.onlineFlag;
    }

    /**
     * Gets the value of the onlineFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onlineFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnlineFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificDateTime }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificDateTime> getOnlineFrom() {
        if (onlineFrom == null) {
            onlineFrom = new ArrayList<SharedTypeSiteSpecificDateTime>();
        }
        return this.onlineFrom;
    }

    /**
     * Gets the value of the onlineTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onlineTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnlineTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificDateTime }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificDateTime> getOnlineTo() {
        if (onlineTo == null) {
            onlineTo = new ArrayList<SharedTypeSiteSpecificDateTime>();
        }
        return this.onlineTo;
    }

    /**
     * Gets the value of the availableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvailableFlag() {
        return availableFlag;
    }

    /**
     * Sets the value of the availableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvailableFlag(Boolean value) {
        this.availableFlag = value;
    }

    /**
     * Gets the value of the searchableFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchableFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchableFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificBoolean }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificBoolean> getSearchableFlag() {
        if (searchableFlag == null) {
            searchableFlag = new ArrayList<SharedTypeSiteSpecificBoolean>();
        }
        return this.searchableFlag;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductImages }
     *     
     */
    public ComplexTypeProductImages getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductImages }
     *     
     */
    public void setImages(ComplexTypeProductImages value) {
        this.images = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the thumbnail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * Sets the value of the thumbnail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbnail(String value) {
        this.thumbnail = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the taxClassId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxClassId() {
        return taxClassId;
    }

    /**
     * Sets the value of the taxClassId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxClassId(String value) {
        this.taxClassId = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the manufacturerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * Sets the value of the manufacturerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerName(String value) {
        this.manufacturerName = value;
    }

    /**
     * Gets the value of the manufacturerSku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerSku() {
        return manufacturerSku;
    }

    /**
     * Sets the value of the manufacturerSku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerSku(String value) {
        this.manufacturerSku = value;
    }

    /**
     * Gets the value of the searchPlacement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchPlacement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchPlacement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificInt }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificInt> getSearchPlacement() {
        if (searchPlacement == null) {
            searchPlacement = new ArrayList<SharedTypeSiteSpecificInt>();
        }
        return this.searchPlacement;
    }

    /**
     * Gets the value of the searchRank property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchRank property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchRank().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificInt }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificInt> getSearchRank() {
        if (searchRank == null) {
            searchRank = new ArrayList<SharedTypeSiteSpecificInt>();
        }
        return this.searchRank;
    }

    /**
     * Gets the value of the sitemapIncludedFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sitemapIncludedFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSitemapIncludedFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificBoolean }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificBoolean> getSitemapIncludedFlag() {
        if (sitemapIncludedFlag == null) {
            sitemapIncludedFlag = new ArrayList<SharedTypeSiteSpecificBoolean>();
        }
        return this.sitemapIncludedFlag;
    }

    /**
     * Gets the value of the sitemapChangefrequency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sitemapChangefrequency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSitemapChangefrequency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificSiteMapChangeFrequency }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificSiteMapChangeFrequency> getSitemapChangefrequency() {
        if (sitemapChangefrequency == null) {
            sitemapChangefrequency = new ArrayList<SharedTypeSiteSpecificSiteMapChangeFrequency>();
        }
        return this.sitemapChangefrequency;
    }

    /**
     * Gets the value of the sitemapPriority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sitemapPriority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSitemapPriority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SharedTypeSiteSpecificSiteMapPriority }
     * 
     * 
     */
    public List<SharedTypeSiteSpecificSiteMapPriority> getSitemapPriority() {
        if (sitemapPriority == null) {
            sitemapPriority = new ArrayList<SharedTypeSiteSpecificSiteMapPriority>();
        }
        return this.sitemapPriority;
    }

    /**
     * Gets the value of the pageAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypePageAttributes }
     *     
     */
    public ComplexTypePageAttributes getPageAttributes() {
        return pageAttributes;
    }

    /**
     * Sets the value of the pageAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypePageAttributes }
     *     
     */
    public void setPageAttributes(ComplexTypePageAttributes value) {
        this.pageAttributes = value;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SharedTypeSiteSpecificCustomAttributes }
     *     
     */
    public SharedTypeSiteSpecificCustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedTypeSiteSpecificCustomAttributes }
     *     
     */
    public void setCustomAttributes(SharedTypeSiteSpecificCustomAttributes value) {
        this.customAttributes = value;
    }

    /**
     * Gets the value of the bundledProducts property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductBundledProducts }
     *     
     */
    public ComplexTypeProductBundledProducts getBundledProducts() {
        return bundledProducts;
    }

    /**
     * Sets the value of the bundledProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductBundledProducts }
     *     
     */
    public void setBundledProducts(ComplexTypeProductBundledProducts value) {
        this.bundledProducts = value;
    }

    /**
     * Gets the value of the retailSetProducts property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductRetailSetProducts }
     *     
     */
    public ComplexTypeProductRetailSetProducts getRetailSetProducts() {
        return retailSetProducts;
    }

    /**
     * Sets the value of the retailSetProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductRetailSetProducts }
     *     
     */
    public void setRetailSetProducts(ComplexTypeProductRetailSetProducts value) {
        this.retailSetProducts = value;
    }

    /**
     * Gets the value of the productSetProducts property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductProductSetProducts }
     *     
     */
    public ComplexTypeProductProductSetProducts getProductSetProducts() {
        return productSetProducts;
    }

    /**
     * Sets the value of the productSetProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductProductSetProducts }
     *     
     */
    public void setProductSetProducts(ComplexTypeProductProductSetProducts value) {
        this.productSetProducts = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductOptions }
     *     
     */
    public ComplexTypeProductOptions getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductOptions }
     *     
     */
    public void setOptions(ComplexTypeProductOptions value) {
        this.options = value;
    }

    /**
     * Gets the value of the variations property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductVariations }
     *     
     */
    public ComplexTypeProductVariations getVariations() {
        return variations;
    }

    /**
     * Sets the value of the variations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductVariations }
     *     
     */
    public void setVariations(ComplexTypeProductVariations value) {
        this.variations = value;
    }

    /**
     * Gets the value of the productLinks property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductProductLinks }
     *     
     */
    public ComplexTypeProductProductLinks getProductLinks() {
        return productLinks;
    }

    /**
     * Sets the value of the productLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductProductLinks }
     *     
     */
    public void setProductLinks(ComplexTypeProductProductLinks value) {
        this.productLinks = value;
    }

    /**
     * Gets the value of the categoryLinks property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductCategoryLinks }
     *     
     */
    public ComplexTypeProductCategoryLinks getCategoryLinks() {
        return categoryLinks;
    }

    /**
     * Sets the value of the categoryLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductCategoryLinks }
     *     
     */
    public void setCategoryLinks(ComplexTypeProductCategoryLinks value) {
        this.categoryLinks = value;
    }

    /**
     * Gets the value of the classificationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexTypeProductClassificationCategory }
     *     
     */
    public ComplexTypeProductClassificationCategory getClassificationCategory() {
        return classificationCategory;
    }

    /**
     * Sets the value of the classificationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexTypeProductClassificationCategory }
     *     
     */
    public void setClassificationCategory(ComplexTypeProductClassificationCategory value) {
        this.classificationCategory = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public SimpleTypeImportMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeImportMode }
     *     
     */
    public void setMode(SimpleTypeImportMode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

}
