//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 10:11:34 AM PST 
//


package com.pacsun.catalog.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleType.Sorting.Mode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="simpleType.Sorting.Mode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="value-name"/>
 *     &lt;enumeration value="value-count"/>
 *     &lt;enumeration value="category-position"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "simpleType.Sorting.Mode", namespace = "http://www.demandware.com/xml/impex/catalog/2006-10-31")
@XmlEnum
public enum SimpleTypeSortingMode {

    @XmlEnumValue("value-name")
    VALUE_NAME("value-name"),
    @XmlEnumValue("value-count")
    VALUE_COUNT("value-count"),
    @XmlEnumValue("category-position")
    CATEGORY_POSITION("category-position");
    private final String value;

    SimpleTypeSortingMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimpleTypeSortingMode fromValue(String v) {
        for (SimpleTypeSortingMode c: SimpleTypeSortingMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
